spring.datasource:
  url: ${JDBC_URL:jdbc:h2:./operaton-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
  username: ${JDBC_USER:sa}
  password: ${JDBC_PASSWORD:sa}

operaton.bpm:
  history-level: audit
  authorization:
    enabled: true
  # CSP header configuration
  webapp:
    header-security:
      content-security-policy-value: "base-uri 'self';
                                      script-src $NONCE 'strict-dynamic' 'unsafe-eval' https: 'self' 'unsafe-inline';
                                      style-src 'unsafe-inline' 'self';
                                      connect-src ${keycloak.url} 'self';
                                      default-src 'self';
                                      img-src 'self' data:;
                                      block-all-mixed-content;form-action 'self';
                                      frame-ancestors 'none';object-src 'none';
                                      sandbox allow-forms allow-scripts allow-same-origin allow-popups allow-downloads"

server:
  port: 8080

# Metrics & Health
management:
  endpoint.health.probes.enabled: true
  endpoints:
    web.exposure.include: env,health,info,metrics


# Externalized Keycloak configuration
keycloak:
  # Keycloak access for the Identity Provider plugin.
  url: http://localhost:9000

  # Keycloak JWT Client configuration
  jwt:
    realm: operaton
    client.id: operaton-jwt

  # Keycloak Operaton Identity Service
  plugin:
    client.id: operaton-identity-service
    client.secret: FOZQuxYwfuvb9R708askvn9XkZMfwlKp

# Spring Boot Security OAuth2 SSO
spring.security:
  oauth2:
    resource-server:
      jwt:
        issuer-uri: ${keycloak.url}/realms/operaton

# Operaton Cockpit JWT Plugin
plugin.cockpit.keycloak:
  keycloakUrl: ${keycloak.url}
  realm: ${keycloak.jwt.realm}
  clientId: ${keycloak.jwt.client.id}

# Operaton Keycloak Identity Provider Plugin
plugin.identity.keycloak:
  keycloakIssuerUrl: ${keycloak.url}/realms/operaton
  keycloakAdminUrl: ${keycloak.url}/admin/realms/operaton
  clientId: ${keycloak.plugin.client.id}
  clientSecret: ${keycloak.plugin.client.secret}
  useEmailAsOperatonUserId: false
  useUsernameAsOperatonUserId: true
  useGroupPathAsOperatonGroupId: true
  administratorGroupName: operaton-admin
  disableSSLCertificateValidation: true

logging.level.org.springframework.security: TRACE
