# Find more available configuration properties on the following pages of the documentation.
# https://docs.camunda.org/manual/latest/user-guide/camunda-bpm-run/#configure-camunda-bpm-run
# https://docs.camunda.org/manual/latest/user-guide/spring-boot-integration/configuration/#camunda-engine-properties

operaton.bpm:
  run:
# https://docs.camunda.org/manual/latest/user-guide/camunda-bpm-run/#cross-origin-resource-sharing
    cors:
      enabled: true
      allowed-origins: "*"
  authorization.enabled: true
  
# datasource configuration is required
spring.datasource:
  url: jdbc:h2:./operaton-h2-default/process-engine;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE
  driver-class-name: org.h2.Driver
  username: sa
  password: sa

# Operaton Keycloak Identity Provider Plugin
# Externalized Keycloak configuration
keycloak:
  # Keycloak access for the Identity Provider plugin.
  host: ${KEYCLOAK_HOST}
  realm: ${KEYCLOAK_REALM:operaton}
  # Keycloak Operaton Identity Client
  client.id: ${KEYCLOAK_CLIENT_ID:operaton-identity-service}
  client.secret: ${KEYCLOAK_CLIENT_SECRET}

plugin.identity.keycloak:
  keycloakIssuerUrl: ${keycloak.host}/auth/realms/${keycloak.realm}
  keycloakAdminUrl: ${keycloak.host}/auth/admin/realms/${keycloak.realm}
  clientId: ${keycloak.client.id}
  clientSecret: ${keycloak.client.secret}
  useEmailAsOperatonUserId: false
  useUsernameAsOperatonUserId: true
  useGroupPathAsOperatonGroupId: true
  administratorGroupName: operaton-admin
  disableSSLCertificateValidation: true